### ISSUE TITLE
Amiibos wont scan

### ISSUE THREAD

**Issue by AlfieMortimer** [Golem642/NFCheckRem#2]
I'm not sure If I'm using this wrong but I followed all the steps and all it did was disable my ability to scan amiibos on the 3ds. I've made sure all of the luna settings are on but nothing has worked

**Comment by Golem642** [comment]
Hello, make sure wumiibo is disabled as it replaces the NFC module entirely

What console model are you using ?

**Comment by AlfieMortimer** [comment]
I don't think I have ever installed wumiibo onto my 3ds. I have a new 2ds xl.

**Comment by Golem642** [comment]
Make sure you downloaded the New 3DS/new 2ds version of the patch.
Could you tell me the content of your /luma/sysmodules folder please ?

**Comment by AlfieMortimer** [comment]
0004013000004002.ips is the only thing in my sysmodules folder. im reinstalling it now to make sure its the New version.

**Comment by AlfieMortimer** [comment]
Ive done a bit of testing at it looks like whenever 0004013000004002.ips is present it disables the use of amiibo. when I remove it without any other changes to anything else it amiibos start to scan again.

**Comment by Golem642** [comment]
Huh that's strange. Could you do the following as described in the readme ?

- Open GodMode9, press the HOME button -> Title manager -> NAND / TWL
- Navigate to 0004013020004002
- Press (A) -> Open title folder
- Select the .app file, press (A) -> NCCH image options... -> Extract .code
- You now have in your SD card in /gm9/out/ a 0004013020004002.dec.code

And then send me the file here, I'll compare it with the new 3DS one i have

**Comment by Golem642** [comment]
I mean it works for me, both for locked and unlocked tags (see below, one tag is write-locked the other is unlocked). Do as said above and I'll see if i can do something about it

![IMG_20240924_234312.jpg](https://github.com/user-attachments/assets/71431218-9900-423b-930e-479627bbf0cb)

![IMG_20240924_234619.jpg](https://github.com/user-attachments/assets/9a350cfa-1fe4-43ce-a5c6-c2d78b3dacc8)

https://github.com/user-attachments/assets/7e8e2664-4856-4850-b822-23ff10c9100b

**Comment by AlfieMortimer** [comment]
[File.zip](https://github.com/user-attachments/files/17121989/File.zip)
I couldn't send the raw file so I sent it in a zip

**Comment by Golem642** [comment]
Ok i've just done some verifications, the file you've given me is the same one that i extracted from my 3DS so it's very weird.
Could you check your luma3DS version ? (hold SELECT on boot and send an image of your console screens)

**Comment by AlfieMortimer** [comment]
![17272998064994536081823469855602](https://github.com/user-attachments/assets/4e929336-0e35-4677-a48d-1bf140de951c)

**Comment by Golem642** [comment]
I see you're a version under, try to update your Luma and see if it changes anything

**Comment by Golem642** [comment]
Do you still have the problem ?

**Comment by AlfieMortimer** [comment]
I've managed to get amiibos to scan now however they do not seem to have been unlocked. Sorry for the lack of replies I've been quite ill the past few days.

**Comment by Golem642** [comment]
Nono don't worry, I hope your illness isn't too much.

In any case, if you want to create unlocked tags, you'd have to use the custom version of Tagmo that you can find in the releases of this repo (just go and write a new tag like you'd normally do but with this app)

Keep in mind you're going to need NTAG215 NFC tags and you cannot create an unlocked tag on top of an already locked/normal amiibo. But you can replace your already unlocked tag (or a blank one) with a new version/model or anything else anytime, that's the magic !
And of course with this patch you can scan both normal amiibos/locked tags, and unlocked ones

Also, just a quick question: what did you do exactly to make it work ?

**Comment by Golem642** [comment]
> Also, just a quick question: what did you do exactly to make it work ?

^ If you could please answer this when you have a bit of time, that could be helpful in the future

**Comment by Golem642** [comment]
I'm going to close this now, feel free to reopen or add a reply if needed.
I hope your condition got better
